name: Go package

on: 
  - workflow_dispatch
  - push

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.BEAUTE_TOKEN }}
      IMAGE_NAME: cor_cmd_couchbase
      IMAGE_TAG: 1.0.${{ github.run_number }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Build
        working-directory: scm/golang/core_msvc/command/cor_cmd_couchbase
        run: |
          sudo docker system prune -af
          sudo docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --rm=false --no-cache
          sudo docker run -d --name ${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }} -p 3015:3015 ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          sudo docker ps -a
          sudo docker inspect ${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}
          sudo docker logs -f ${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}
    
