name: Build Image

on:
  push:   
  pull_request:
    types: [closed, assigned, opened, reopened] 

env:
  IMAGE_NAME: cor_cmd_couchbase
  IMAGE_TAG: ${{ github.run_number }}

jobs:
  build-push-docker-image:
   runs-on: ubuntu-latest
   permissions:
     contents: read
     packages: write
     id-token: write
   strategy:
      matrix:
        go-version: [ '1.17' ]
  
   steps:
    - name: Set up Go 
      id: go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    
    - name: checkout repository
      uses: actions/checkout@v3
      
        
   
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Log into github registry ${{ env.REGISTRY }}
      uses: docker/login-action@v1
      with:
        username: syamoliam
        password: Syamoliam143$

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: syamoliam/githubactions
      
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
